jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Clone repository
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Build
      run: './gradlew :app:assembleDebug

        '
name: Gralde check
on:
  repository_dispatch:
    types: trigger-ga___gradle-check.yml
